### ISSUE TITLE
Make a docker file for Yacy grid parser and deploy it to google cloud.

### ISSUE THREAD

**Issue by nikhilrayaprolu** [yacy/yacy_grid_parser#1]
It is better to have different containers for each of the micro services while in deployment. Create a docker file and deploy it to Google cloud for yacy_grid_parser.

**Comment by Orbiter** [comment]
This Grid component uses (like all other YaCy Grid elements) the Dockerfile from yacy_grid_mcp, which is embedded as git submodule (see readme). The dockerfile is then also a part of this Grid service and can be found in https://github.com/yacy/yacy_grid_mcp/blob/development/docker/Dockerfile
