### ISSUE TITLE
Getting compilation error :compileJava failed

### ISSUE THREAD

**Issue by harshit98** [yacy/yacy_grid_parser#2]
I was working on issue #1. While building Docker image, I get this compilation error:

![28579277-cf9c1a5a-7179-11e7-828c-ace82676a6bb](https://user-images.githubusercontent.com/22245418/29567170-facf6b0e-8769-11e7-9035-ff7299625565.png)

Even manual build is giving a compilation error. This issue can be referred here: https://github.com/yacy/yacy_grid_crawler/issues/2

**Comment by sudheesh001** [comment]
<strike>Can you give the list of errors that it says before the message `59 errors`?</strike>

I could reproduce this when you do not do `--recursive` which do not download the submodules. Can you check if the `yacy_grid_mcp` folder insider submodules actually has any content?

**Comment by Orbiter** [comment]
same cause as in #1: the submodule was not checked out.
