### ISSUE TITLE
Flatjson file loader

### ISSUE THREAD

**Issue by yuriikulish** [yacy/yacy_grid_parser#4]
I was able to set up yacy grid parser and convert warc file as described in documentation. I used next list of command

wget -r -l3 "https://www.publicplan.de/" --warc-file="publicplan.de"

curl -X POST -F "sourcebytes=@publicplan.de.warc.gz" -F "flatfile=true" -o "publicplan.de.flatjson" http://localhost:8500/yacy/grid/parser/parser.json

I put  "publicplan.de.flatjson" to yacy_search_server/DATA/SURROGATES/in/ path but it wasn't automatically parsed.

1. Did I do something wrong? Does yacy supports all kind of files for automatic indexing?
2. Can I convert WARC to xml not to flatjson?
3. What is the best way to index WARC files?

**Comment by Orbiter** [comment]
This microservice (the parser) is connected to yacy_grid_mcp, the broker and connector between the YaCy Grid components. There is no connection between legacy YaCy (yacy_search_server) and the Grid Parser (yet), so your test case cannot work because it is not supposed to work like this.
